version: '3.8'

# Define services
services:

  # Backend service
  backend:
    build:
      context: ./Techdome-backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - PORT=5000
      - DB=mongodb://database:27017/techdome
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - app_network

  # Frontend service
  frontend:
    build:
      context: ./Techdome-frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      - REACT_APP_BASE_URL=http://localhost:5000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network

  # Database service
  database:
    image: mongo:latest
    container_name: database
    ports:
      - "27017:27017"
    networks:
      - app_network
    volumes:
      - mongo_data:/data/db

# Define volumes
volumes:
  mongo_data:

# Define networks
networks:
  app_network:

