apiVersion: apps/v1
kind: Deployment
metadata:
  name: techdome-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techdome-database
  template:
    metadata:
      labels:
        app: techdome-database
    spec:
      containers:
      - name: database
        image: mongo:latest
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  selector:
    app: techdome-database
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP
